=== sio2sio2/LM/docs/_downloads/22cd219b94b0b29c24b13111d303486a/concesionario.schema.json
{
   "$schema": "https://json-schema.org/draft/2020-12/schema",
   "$id": "concesionario.schema.json",

   "title": "Concesionario",
   "description": "Ventas de un concesinario",

   "type": "object",
   "properties": {
      "concesionario": {
         "description": "Nombre del concesionario",
         "type": "string"
      },
      "clientes": {
         "description": "Lista de clientes",
         "type": "array",
         "items": {
            "description": "Cliente del concesionario",
            "$ref": "#/$defs/persona"
         }
      },
      "modelos": {
         "description": "Lista de modelos de la marca",
         "type": "array",
         "items": {"$ref": "#/$defs/modelo"}
      },
      "coches": {
         "descripcion": "Coches para la venta",
         "type": "array",
         "items": {"$ref": "#/$defs/coche"}
      }
   },
   "required": ["concesionario"],
   "additionalProperties": false,

   "$defs": {
      "persona": {
         "type": "object",
         "properties": {
            "id": {"$ref": "#/$defs/identificador"},
            "dni": {
               "type": "string",
               "pattern": "^[0-9]{8}[A-Z]$"
            },
            "nombre": {
               "type": "string"
            },
            "direccion": {"$ref": "#/$defs/direccion"}
         },
         "required": ["id", "nombre"],
         "additionalProperties": false
      },
      "direccion": {
         "description": "Dirección postal",
         "type": "object",
         "properties": {
            "domicilio": { "type": "string" },
            "cp": { "type": "integer" },
            "poblacion": { "type": "string" }
         },
         "required": ["domicilio", "cp", "poblacion"],
         "additionalProperties": false
      },
      "identificador": {
         "type": "integer",
         "minimum": 1
      },
      "modelo": {
         "type": "object",
         "additionalProperties": false,
         "required": ["id", "nombre"],
         "properties": {
            "id": {"$ref": "#/$defs/identificador"},
            "nombre": {"type": "string"},
            "cilindrada": {
               "type": "integer",
               "minimum": 1
            },
            "cv": {
               "type": "integer",
               "minimum": 1
            },
            "velmax": {
               "type": "integer",
               "minimum": 1
            },
            "plazas": {
               "type": "integer",
               "minimum": 1
            }
         }
      },
      "coche": {
         "description": "Coche en venta. Nuevo no puede tener 'km'; km0, puede pero no más de 100; '2mano' debe tenerlos.",
         "type": "object",
         "unevaluatedProperties": false,
         "required": ["id", "modelo", "tipo"],
         "properties": {
            "id": {"$ref": "#/$defs/identificador"},
            "modelo": {"$ref": "#/$defs/identificador"},
            "reservado": {
               "description": "Cliente que reserva el coche o false",
               "default": false,
               "oneOf": [
                  {"$ref": "#/$defs/identificador"},
                  {"const": false}
               ]
            }
         },
         "oneOf": [
            {
               "properties": {
                  "tipo": { "const": "2mano" },
                  "km": {"type": "integer", "minimum": 0}
               },
               "required": ["km"]
            },
            {
               "properties": {
                  "tipo": { "const": "nuevo" }
               }
            },
            {
               "properties": {
                  "tipo": {"const": "km0"},
                  "km": {"type": "integer", "minimum": 0, "maximum": 100}
               }
            }
         ]
      }
   }
}

=== sio2sio2/LM/docs/_downloads/ecf703e56b0d428a8a76c5fb1a2cd12a/concesionario.json
{
   "concesionario": "SEAT",
   "clientes": [
      {
         "id": 1,
         "dni": "12345678Z",
         "nombre": "Perico de los Palotes",
         "direccion": {
            "domicilio": "c/ AAAAA, 22",
            "cp": 12345,
            "poblacion": "Villaarriba"
         }
      },
      {
         "id": 2,
         "dni": "012345678L",
         "nombre": "María Bermudo",
         "direccion": {
            "domicilio": "c/ BBBBB, 21",
            "cp": 54321,
            "poblacion": "Villaabajo"
         }
      }
   ],
   "modelos": [
      {
         "id": 1,
         "nombre": "León",
         "cilindrada": 2000,
         "cv": 140,
         "velmax": 220,
         "plazas": 5
      },
      {
         "id": 2,
         "nombre": "Ibiza",
         "cilindrada": 1800,
         "cv": 120,
         "velmax": 200,
         "plazas": 5
      }
   ],
   "coches": [
      {
         "id": 1,
         "modelo": 1,
         "tipo": "nuevo",
         "reservado": 1
      },
      {
         "id": 2,
         "modelo": 1,
         "tipo": "2mano",
         "km": 50000
      },
      {
         "id": 3,
         "modelo": 2,
         "tipo": "km0"
      },
      {
         "id": 4,
         "modelo": 2,
         "tipo": "2mano",
         "km": 132000,
         "reservado": 2
      }
   ]
}
