=== sio2sio2/LM/source/99.ejercicios/soluciones/prestamos/biblioteca.schema.json
{
   "$schema": "https://json-schema.org/draft/2020-12/schema",
   "$id": "biblioteca.schema.json",

   "title": "Biblioteca",
   "description": "Préstamos de una biblioteca",

   "type": "object",
   "properties": {
      "biblioteca": {
         "description": "Nombre de la biblioteca",
         "type": "string"
      },
      "socios": {
         "description": "Socio de la biblioteca",
         "type": "array",
         "items": { "$ref": "#/$defs/persona" }
      },
      "catalogo": {
         "description": "Libros que tiene la biblioteca",
         "type": "array",
         "items": {"$ref": "#/$defs/libro"},
         "minItems": 1,
         "uniqueItems": true
      },
      "prestamos": {
         "description": "Lista de préstamos de la biblioteca",
         "type": "array",
         "items": {"$ref": "#/$defs/prestamo"},
         "uniqueItems": true
      }
   },
   "required": ["biblioteca", "catalogo"],
   "additionalProperties": false,

   "$defs": {
      "persona": {
         "type": "object",
         "properties": {
            "id": {"$ref": "#/$defs/identificador"},
            "dni": {
               "type": "string",
               "pattern": "[0-9]{8}[A-Z]"
            },
            "nombre": {
               "type": "string"
            },
            "direccion": {"$ref": "#/$defs/direccion"}
         }
      },
      "direccion": {
         "description": "Dirección postal",
         "type": "object",
         "properties": {
            "domicilio": { "type": "string" },
            "cp": { "type": "integer" },
            "poblacion": { "type": "string" }
         },
         "required": ["domicilio", "cp", "poblacion"],
         "additionalProperties": false
      },
      "libro": {
         "description": "Libro de lña bibliotecaa",
         "type": "object",
         "properties": {
            "isbn": { "type": "string" },
            "nombre": { "type": "string" },
            "autor": { "type": "string" },
            "año": { "type": "integer" },
            "editorial": { "type": "string" },
            "ejemplares": {
               "type": "array",
               "items": { "$ref": "#/$defs/identificador" },
               "uniqueItems": true
            }
         },
         "required": ["isbn", "nombre"],
         "additionalProperties": false
      },
      "identificador": {
         "description": "Campo identificador",
         "type": "integer",
         "minimum": 1
      },
      "prestamo": {
            "type": "object",
            "properties": {
               "ejemplar": { "$ref": "#/$defs/identificador" },
               "lector": { "$ref": "#/$defs/identificador" },
               "fecha": { "type": "string", "format": "date"},
               "plazo": {
                  "description": "Plazo en días",
                  "type": "integer",
                  "minimum": 1
               },
               "devolucion": { "type": "string", "format": "date"}
            },
            "required":  [ "ejemplar", "lector", "fecha", "plazo"],
            "additionalProperties": false
      }
   }
}

=== sio2sio2/LM/_downloads/d242b6d8c1e44da3fbd0653cda58862c/biblioteca.json
{
   "biblioteca": "Biblioteca Municipal",
   "catalogo": [
      {
         "isbn": "id85-359-0277-5",
         "nombre": "Don Quijote de La Mancha",
         "autor": "Miguel de Cervantes Saavedra",
         "año": 1997,
         "editorial": "Castalia",
         "ejemplares": [1, 2]
      },
      {
         "isbn": "id85-359-0277-6",
         "nombre": "Historia de la vida del Buscón",
         "autor": "Francisco de Quevedo",
         "año": 2002,
         "editorial": "Alianza",
         "ejemplares": [6, 7]
      }
   ],
   "socios": [
      {
         "numero": 1,
         "dni": "12345678Z",
         "nombre": "Perico de los Palotes",
         "direccion": {
            "domicilio": "c/ AAAA, 22",
            "cp": 12345,
            "poblacion": "Villaarriba"
         }
      },
      {
         "numero": 2,
         "dni": "01234567L",
         "nombre": "Mercedes Verdugo Cordero",
         "direccion": {
            "domicilio": "c/ BBBB, 23",
            "cp": 54321,
            "poblacion": "Villaabajo"
         }
      }
   ],
   "prestamos": [
      { 
         "ejemplar": 1,
         "lector": 1,
         "fecha": "2018-10-02",
         "plazo": 10,
         "devolucion": "2018-10-10"
      },
      { 
         "ejemplar": 6,
         "lector": 2,
         "fecha": "2018-09-01",
         "plazo": 15
      },
      { 
         "ejemplar": 7,
         "lector": 1,
         "fecha": "2018-10-15",
         "plazo": 10
      }
   ]
}
