=== sio2sio2/LM/source/99.ejercicios/soluciones/ayuntamiento/dtd/ayuntamiento.dtd
<!ELEMENT habitantes (persona+)>
<!ATTLIST habitantes ayuntamiento      CDATA    #REQUIRED>

<!ELEMENT persona (nombre, apellidos, direccion, tlfo, origen, padre?, madre?)>
<!ATTLIST persona id       ID             #REQUIRED
                  padre    IDREF          #IMPLIED
                  madre    IDREF          #IMPLIED
                  sexo     (hombre|mujer) #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT tlfo (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT padre (#PCDATA)>
<!ELEMENT madre (#PCDATA)>

<!ELEMENT direccion (via, numero, piso, letra)>
<!ELEMENT via (#PCDATA)>
<!ATTLIST via tipo      (calle|callejÃ³n|cuesta|costanilla|plaza|avenida|paseo) "calle">
<!ELEMENT numero (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT letra (#PCDATA)>

=== sio2sio2/LM/docs/_downloads/f1167d2b5559eec5f82f9933f9d3bd55/ayuntamiento.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE habitantes SYSTEM "ayuntamiento.dtd">
<habitantes ayuntamiento="Isla Cristina">
   <persona id="p01">
      <nombre>José Manuel</nombre>
      <apellidos>Pérez Bermúdez</apellidos>
      <direccion>
         <via tipo="avenida">España</via>
         <numero>100</numero>
         <piso>1</piso>
         <letra>A</letra>
      </direccion>
      <tlfo>959010203</tlfo>
      <origen>Lepe</origen>
      <padre>Manuel</padre>
      <madre>María</madre>
   </persona>
   <persona id="p02">
      <nombre>María</nombre>
      <apellidos>González Faneca</apellidos>
      <direccion>
         <via tipo="avenida">España</via>
         <numero>100</numero>
         <piso>1</piso>
         <letra>A</letra>
      </direccion>
      <tlfo>959010203</tlfo>
      <origen>Isla Cristina</origen>
      <padre>José</padre>
      <madre>Cristina</madre>
   </persona>
   <persona id="p03" madre="p02" padre="p01">
      <nombre>Manuel</nombre>
      <apellidos>Pérez González</apellidos>
      <direccion>
         <via tipo="avenida">España</via>
         <numero>100</numero>
         <piso>1</piso>
         <letra>A</letra>
      </direccion>
      <tlfo>959010203</tlfo>
      <origen>Isla Cristina</origen>
   </persona>

   <!-- Más personas -->
</habitantes>
