=== sio2sio2/LM/source/99.ejercicios/soluciones/parques/dtd/parques.dtd
<!ELEMENT parques (especie+, parque+)>
<!ATTLIST parques pais     CDATA                #REQUIRED>

<!ELEMENT especie (comun, cientifico)>
<!ATTLIST especie id       ID                   #REQUIRED
                  tipo     (fauna|flora)        #REQUIRED
                  peligro  (bajo|medio|alto)    #REQUIRED>

<!ELEMENT comun (#PCDATA)>
<!ELEMENT cientifico (#PCDATA)>

<!ELEMENT parque (especimen+)>
<!ATTLIST parque id        ID                   #REQUIRED
                 nombre    CDATA                #REQUIRED
                 provincia CDATA                #REQUIRED
                 ca        CDATA                #REQUIRED>

<!ELEMENT especimen EMPTY>
<!ATTLIST especimen ref    IDREF                #REQUIRED
                    ejemplares NMTOKEN          #IMPLIED>

=== sio2sio2/LM/source/99.ejercicios/soluciones/parques/parques.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE parques SYSTEM "parques.dtd">
<parques pais="España">
   <especie id="e01" tipo="fauna" peligro="medio">
      <comun>Lince</comun>
      <cientifico>Lynx pardinus</cientifico>
   </especie>

   <especie id="e02" tipo="flora" peligro="medio">
      <comun>Drago</comun>
      <cientifico>Dracaena draco</cientifico>
   </especie>

   <!-- Mas especies -->

   <parque id="p01" nombre="Doñana" provincia="Huelva" ca="Andalucía" extension="10000" presupuesto="100">
      <especimen ref="e01" ejemplares="150" />
      <especimen ref="e02" />
      <!-- Más especímenes -->
   </parque>

   <!-- Más parques -->
</parques>
